<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFb0eVg5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFb0eVg5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFb0eVg5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFb0eVg5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFb0eVg5\App_KernelDevDebugContainer([
    'container.build_hash' => 'Fb0eVg5',
    'container.build_id' => 'a4d4a73b',
    'container.build_time' => 1714640814,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFb0eVg5');
